# Generated by Django 4.2.4 on 2023-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ethereum_tx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
